<?php

define('AASHAN_ITONICS_DB_TABLE', 'aashan_itonics_employee');

include __DIR__ . '/controllers/aashan_itonics_employee_controller.php';

/**
 * Sets Permissions for Employee Module
 * @return array
 */
function employee_permission() {
  return [
    'manage employee' => [
      'title' => t('Manage Employees (CRUD)'),
      'description' => t('Create, Edit, View and Delete employees')
    ]
  ];
}


/**
 * Binds routes for employee module using hook_menu()
 * @return array
 */
function employee_menu() {
  $routes['/employee'] = [
    'title' => t('Employees'),
    'page callback' => 'aashan_itonics_get_employee_list_a'
  ];

  return $routes;
}


function employee_theme($existing, $type, $theme, $path) {
  $theme['aashan_itonics_employee_list'] = [
    'render element' => 'content',
    'template' => 'aashan_itonics_employee_list',
    'path' => drupal_get_path('module', 'employee') . '/templates/'
  ];
  return $theme;
}
