<?php

define('AASHAN_ITONICS_DB_TABLE', 'aashan_itonics_employee');

include __DIR__ . '/controllers/aashan_itonics_employee_controller.php';

/**
 * Sets Permissions for Employee Module
 * @return array
 */
function employee_permission() {
  return [
    'manage employee' => [
      'title' => t('Manage Employees (CRUD)'),
      'description' => t('Create, Edit, View and Delete employees')
    ]
  ];
}


/**
 * Binds items for employee module using hook_menu()
 * @return array
 */
function employee_menu() {
  $items['employee'] = [
    'title' => t('Employees'),
    'description' => t('View Employees'),
    'page callback' => 'aashan_itonics_get_employee_list',
    'access callback' => user_access('manage employee')
  ];

  $items['employee/create'] = [
    'title' => t('Create Employee'),
    'description' => t('Create Employees'),
    'page callback' => 'drupal_get_form',
    'page arguments' => ['aashan_itonics_create_employee_form'],
    'access callback' => user_access('manage employee')
  ];

  $items['employee/%/delete'] = [
    'title' => t(''),
    'description' => t(''),
    'page callback' => 'aashan_itonics_delete_employee',
    'page arguments' => [1],
    'access callback' => user_access('manage employee')
  ];

  $items['employee/%/edit'] = [
    'title' => t('Edit Employee'),
    'description' => t('Edit Employee'),
    'page callback' => 'drupal_get_form',
    'page arguments' => ['aashan_itonics_edit_employee_form', 1],
    'access callback' => user_access('manage employee')
  ];

  $items['employee/%'] = [
    'title' => t('Employee Details'),
    'description' => t('Employee Details'),
    'page callback' => 'aashan_itonics_employee_details',
    'page arguments' => [1],
    'access callback' => user_access('manage employee')
  ];

  return $items;
}


function employee_theme() {
  $theme['aashan_itonics_employee_list'] = [
    'template' => 'aashan_itonics_employee_list',
    'path' => drupal_get_path('module', 'employee') . '/templates/'
  ];
  $theme['aashan_itonics_employee_view'] = [
    'template' => 'aashan_itonics_employee_view',
    'path' => drupal_get_path('module', 'employee') . '/templates/'
  ];
  return $theme;
}
